from src.purple_star_chart.constructor_classes import Stem, Branch

# reference tables used throughout
_stem_lookup = {
    'jia': Stem(1, 'jia', 'wood'),
    'yi': Stem(0, 'yi', 'wood'),
    'bing': Stem(1, 'bing', 'fire'),
    'ding': Stem(0, 'ding', 'fire'),
    'wu': Stem(1, 'wu', 'earth'),
    'ji': Stem(0, 'ji', 'earth'),
    'geng': Stem(1, 'geng', 'metal'),
    'xin': Stem(0, 'xin', 'metal'),
    'ren': Stem(1, 'ren', 'water'),
    'gui': Stem(0, 'gui', 'water')
}
_stems = list(_stem_lookup)

_branch_lookup = {
    'zi': Branch(1, 'zi', 'rat', 'water'),
    'chou': Branch(0, 'chou', 'ox', 'earth'),
    'yin': Branch(1, 'yin', 'tiger', 'wood'),
    'mao': Branch(0, 'mao', 'rabbit', 'wood'),
    'chen': Branch(1, 'chen', 'dragon', 'earth'),
    'si': Branch(0, 'si', 'snake', 'fire'),
    'wu': Branch(1, 'wu', 'horse', 'fire'),
    'wei': Branch(0, 'wei', 'goat', 'earth'),
    'shen': Branch(1, 'shen', 'monkey', 'metal'),
    'you': Branch(0, 'you', 'bird', 'metal'),
    'xu': Branch(1, 'xu', 'dog', 'earth'),
    'hai': Branch(0, 'hai', 'pig', 'water')
}
_branches = list(_branch_lookup)

    # '': {
    #     'zi': ,
    #     'chou': ,
    #     'yin': ,
    #     'mao': ,
    #     'chen': ,
    #     'si': ,
    #     'wu': ,
    #     'wei': ,
    #     'shen': ,
    #     'you': ,
    #     'xu': ,
    #     'hai': 
    # },
_star_magnitude = {
    'zi_wei': {
        'zi': 4,
        'chou': 0,
        'yin': 1,
        'mao': 1,
        'chen': 2,
        'si': 1,
        'wu': 0,
        'wei': 0,
        'shen': 1,
        'you': 1,
        'xu': 2,
        'hai': 1
    },
    'tian_ji': {
        'zi': 0,
        'chou': 6,
        'yin': 2,
        'mao': 1,
        'chen': 3,
        'si': 4,
        'wu': 0,
        'wei': 6,
        'shen': 2,
        'you': 1,
        'xu': 3,
        'hai': 4
    },
    'tai_yang': {
        'zi': 6,
        'chou': 5,
        'yin': 1,
        'mao': 0,
        'chen': 1,
        'si': 1,
        'wu': 1,
        'wei': 2,
        'shen': 2,
        'you': 4,
        'xu': 5,
        'hai': 6
    },
    'wu_qu': {
        'zi': 1,
        'chou': 0,
        'yin': 2,
        'mao': 3,
        'chen': 0,
        'si': 4,
        'wu': 1,
        'wei': 0, # source presents wu qu twice here, arbitrary decision
        'shen': 2,
        'you': 3,
        'xu': 0,
        'hai': 4
    },
    'tian_tong': {
        'zi': 1,
        'chou': 5,
        'yin': 3,
        'mao': 4,
        'chen': 4,
        'si': 0,
        'wu': 6,
        'wei': 5,
        'shen': 1,
        'you': 4,
        'xu': 4,
        'hai': 0
    },
    'lian_zhen': {
        'zi': 4,
        'chou': 3,
        'yin': 0,
        'mao': 4,
        'chen': 3,
        'si': 6,
        'wu': 4,
        'wei': 3,
        'shen': 0,
        'you': 4,
        'xu': 3,
        'hai': 6
    },
    'tian_fu': {
        'zi': 0,
        'chou': 0,
        'yin': 0,
        'mao': 2,
        'chen': None,
        'si': 2,
        'wu': 1,
        'wei': 0,
        'shen': 2,
        'you': 1,
        'xu': 0,
        'hai': 2
    },
    'tai_yin': {
        'zi': 0,
        'chou': 0,
        'yin': 1,
        'mao': 6,
        'chen': 6,
        'si': 6,
        'wu': 5,
        'wei': 5,
        'shen': 3,
        'you': 5,
        'xu': 1,
        'hai': 0
    },
    'tan_lang': {
        'zi': 1,
        'chou': 0,
        'yin': 4,
        'mao': 3,
        'chen': 0,
        'si': 6,
        'wu': 1,
        'wei': 0,
        'shen': 4,
        'you': 3,
        'xu': 0,
        'hai': 6
    },
    'ju_men': {
        'zi': 1,
        'chou': 5,
        'yin': 0,
        'mao': 0,
        'chen': 6,
        'si': 1,
        'wu': 1,
        'wei': 5,
        'shen': 0,
        'you': 0,
        'xu': 6,
        'hai': 1
    },
    'tian_xiang': {
        'zi': 0,
        'chou': 0,
        'yin': 0,
        'mao': 6,
        'chen': 2,
        'si': 2,
        'wu': 0,
        'wei': 2,
        'shen': 0,
        'you': 6,
        'xu': 2,
        'hai': 2
    },
    'tian_liang': {
        'zi': 0,
        'chou': 1,
        'yin': 0,
        'mao': 0,
        'chen': 0,
        'si': 6,
        'wu': 0,
        'wei': 1,
        'shen': 6,
        'you': 2,
        'xu': 0,
        'hai': 6
    },
    'qi_sha': {
        'zi': 1,
        'chou': 0,
        'yin': 0,
        'mao': 1,
        'chen': 0,
        'si': 4,
        'wu': 1,
        'wei': 0,
        'shen': 0,
        'you': 0,
        'xu': 0,
        'hai': 4
    },
    'po_jun': {
        'zi': 0,
        'chou': 1,
        'yin': 2,
        'mao': 6,
        'chen': 1,
        'si': 4,
        'wu': 0,
        'wei': 1,
        'shen': 2,
        'you': 6,
        'xu': 1,
        'hai': 4
    },
    'lu_cun': {
        'zi': 0,
        'chou': None,
        'yin': 0,
        'mao': 0,
        'chen': None,
        'si': 0,
        'wu': 0,
        'wei': None,
        'shen': 0,
        'you': 0,
        'xu': None,
        'hai': 0
    },
    'wen_chang': {
        'zi': 2,
        'chou': 0,
        'yin': 6,
        'mao': 3,
        'chen': 2,
        'si': 0,
        'wu': 6,
        'wei': 3,
        'shen': 2,
        'you': 0,
        'xu': 6,
        'hai': 3
    },
    'wen_qu': {
        'zi': 2,
        'chou': 0,
        'yin': 4,
        'mao': 1,
        'chen': 2,
        'si': 0,
        'wu': 6,
        'wei': 1, # source prints wu qu twice, arbitrary decision
        'shen': 2,
        'you': 0,
        'xu': 6,
        'hai': 1
    },
    'qing_yang': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'huo_xing': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'ling_xing': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tuo_luo': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'jie_shen': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'di_jie': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_xing': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_yao': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_shang': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'di_kong': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_ku': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_xu': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'hong_luan': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_xi': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_yao': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_shi': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_ma': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_gong': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
    'tian_fu_yi': {
        'zi': ,
        'chou': ,
        'yin': ,
        'mao': ,
        'chen': ,
        'si': ,
        'wu': ,
        'wei': ,
        'shen': ,
        'you': ,
        'xu': ,
        'hai': 
    },
}